credentials:
  usernames:
    abcdef:
      email: abcdef@gmail.com
      name: abcdef
      password: $2b$12$0Ojbcj7mL9aphL2XQ1ZvcuEhhS133WRSkAQvNoAsVB4XqjEVklktq
  cookie:
    expiry_days: 1
    key: some_signature_key # Must be string
    name: some_cookie_name
  preauthorized:
    emails:
    - abcdef@gmail.com
